// Generated by https://quicktype.io
//paste JSON code from Postman route user/1

export interface User {
    id:    number; //lo pasaremos a string cuando lo necesiemos usando toString()
    user:  string;
    email: string;
}
