// Generated by https://quicktype.io
//usamos extensión "paste JSON as code" para copiar desde POSTMAN el endpoint http://localhost:3000/heroes y como nivel superior le ponemos Hero

export interface Hero {
    id:               string;
    superhero:        string;
    publisher:        Publisher;
    alter_ego:        string;
    first_appearance: string;
    characters:       string;
}

export enum Publisher {
    DCComics = "DC Comics",
    MarvelComics = "Marvel Comics",
}
